FROM alpine:latest as builder

ENV TZ=Asia/Istanbul

RUN apk update
RUN apk upgrade
RUN apk install tzdata -y

# Installing & Building TDLib
RUN apk add --update alpine-sdk linux-headers git zlib-dev openssl-dev gperf php cmake
RUN git clone https://github.com/tdlib/td.git
WORKDIR td
RUN rm -rf build
RUN mkdir build
WORKDIR build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ..
RUN cmake --build . --target install

FROM apline:latest

